apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat-backend
        image: toshith2005/chat-backend
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          value: "mongodb+srv://toshith23bce8216_db_user:yqb0yYdO9FB0SCwI@cluster0.67bntpx.mongodb.net/chatDB"